version: "3.8"

services:
  nvim:
    image: danieiff/dotfiles:latest
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
    volumes:
      # [path_to_projects]:/root/workspace
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/app
        target: /app
