on:
  push:
    paths:
      - corne-wireless-zmk-config/**
  pull_request:
    paths:
      - corne-wireless-zmk-config/**
  workflow_dispatch:

jobs:
  build:
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    uses: petejohanson/zmk/.github/workflows/build-user-config.yml@feat/pointers-move-scroll
    with:
      build_matrix_path: "corne-wireless-zmk-config/build.yaml"
      config_path: "corne-wireless-zmk-config"
